### ISSUE TITLE
Huge products in iPhone with default Nosto CSS

### ISSUE THREAD

**Issue by pivulic** [Nosto/nosto-magento2#13]
## Problem

In iPhone responsive view and using Nosto's default template/CSS on recommendations, slots shows 1 product / row that takes half of the screen size, while the regular products shows as 2 / row.

See: http://www.vaimo.com/snaps/pablo.ivulic/nosto-m2-category-default-preview.png
## Expected Result

Show smaller products, the same size (or smaller) than the regular products. At least 2 products / row, otherwise the user will have to scroll a lot.

Compare with iPad view: http://www.vaimo.com/snaps/pablo.ivulic/nosto-m2-ipad-responsive-ok.png
## How to recreate
1. Create a new Nosto account without modifying any slots settings/templates/CSS.
2. Preview the frontend, i.e. category or product page (the same goes for all other views)

**Comment by hannunosto** [comment]
This will be handled on a template side. I'll have our UX guys to create new default templates for Magento 2.

**Comment by mridang** [comment]
<img width="577" alt="screen shot 2017-04-11 at 20 49 22" src="https://cloud.githubusercontent.com/assets/327432/24936558/655ad56a-1ef8-11e7-9b12-4389f1e52baf.png">

Sorry it's taken so long to get to this issue. We've actually fixed these a few months ago with our new templates. I've attached a screenshot that shows how the slots look on an iPhone 6.
