### ISSUE TITLE
Mysql debug-log enabled

### ISSUE THREAD

**Issue by AndreKlang** [Nosto/nosto-magento2#182]
In your di.xml, you do this: http://devdocs.magento.com/guides/v2.0/config-guide/log/log-db.html

That activates a log of db-queries to file in var/debug/db.log, after a few days that file is HUGE!

Please remove ```<preference for="Magento\Framework\DB\LoggerInterface" type="Magento\Framework\DB\Logger\File" />```

It was added in this commit: 9868b58c19628bd7acf9b237c9ceef329a42be8e

**Comment by chenliangde** [comment]
Fixed in 2.3.9
