### ISSUE TITLE
Make Nosto configurations available in M2 command line tool

### ISSUE THREAD

**Issue by hannunosto** [Nosto/nosto-magento2#202]
Currently you cannot modify some Nosto config values with `bin/magento config:set` since those values cannot be changed from store admin. Following configurations should be available in command line tool (especially needed for automatic deployments)
* nosto_tagging/settings/tokens
* nosto_tagging/settings/account
* nosto_tagging/installation/id

**Comment by hannunosto** [comment]
This is handled by the CLI installer

**Comment by supercid** [comment]
Fixed in #227
