### ISSUE TITLE
Add support for previewing the order-confirmation page

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-magento2#204]
For debugging, it would be handy to preview the order confirmation page. Yireo seems to have a module that allows you to do this. I don't think we should roll this functionality into our codebase for fear of introducing a security hole but instead use their extension to preview it. 
Our extension would check if the Yireo extension is installed and if so, would generate a preview link to their controller. 

https://github.com/yireo/Yireo_CheckoutTester2

**Comment by supercid** [comment]
No longer an issue
