### ISSUE TITLE
Handle the caching rules for full page cache & Varnish

### ISSUE THREAD

**Issue by hannunosto** [Nosto/nosto-magento2#22]
- if the cacheable="false" is set for customer and cart blocks Varnish seems to skip the whole FPC

**Comment by avra911** [comment]
Hello,

Why the issue is closed? Until 1.1.0 this is still a bug.

I think is better and more logic to leave is open.

**Comment by hannunosto** [comment]
Hey @avra911 thanks for reminding me. 1.1.0 is now released and the cart & customer tagging are rendered using Knockout.js

**Comment by avra911** [comment]
Hi, @hannunosto! Thanks a lot for quick feedback on this!

Happy new year!
