### ISSUE TITLE
Child product should be indexed to nosto if it visible individually

### ISSUE THREAD

**Issue by chenliangde** [Nosto/nosto-magento2#230]
https://github.com/Nosto/nosto-magento2/blob/72e88e2493a38cff1d718ddd2466840327a9182b/Model/Product/Service.php#L196

If the child product is visible individually, it should be indexed to nosto

**Comment by hannunosto** [comment]
This would leave into attribution errors and prolly other issues as well. Let's revise this if we get a solid case where this is needed.
