### ISSUE TITLE
 Invalid product update payload 

### ISSUE THREAD

**Issue by evilprophet** [Nosto/nosto-magento2#249]
Environment:
- Magento 2.1.10
- Nosto 2.7.0

Description:
After the request to Magento API to update the product in system.log I see error - content in the attached file.
[nosto_error.txt](https://github.com/Nosto/nosto-magento2/files/1855902/nosto_error.txt)

I used `PUT    /V1/products/:sku`
With body like this:
`{
   "product":{
      "sku":"SKU",
      "type_id": "simple",
      "name":"NAME",
      "price":"45",
      "status":"1",
      "attribute_set_id":4,
      "custom_attributes":[
         {"attribute_code":"special_price","value":"27"},
         {"attribute_code":"tax_class_id","value":"4"}
      ],
      "extension_attributes":{
         "stock_item":{
            "is_in_stock":true,
            "qty":460
         }
      }
   }
}`

**Comment by hannunosto** [comment]
Hi @evilprophet, I believe I found the failed request from our logs and it seems that the parent product's (configurable product) `image_url` attribute is `null`. Image URL is mandatory field for Nosto's products and that is why our API returns an error. You can verify this by for example adding some placeholder image as a product URL. 

If you cannot get around this issue can you please contact Nosto's support. We might need your Nosto account info and more details to dive deeper into this.

**Comment by evilprophet** [comment]
Hi @hannunosto 
Thanks for the answer, this is more strange because in the shop we don't have configurable products.
I'll contact with Nosto support.
