### ISSUE TITLE
Please release fix for 'store' attribute

### ISSUE THREAD

**Issue by tereshvti** [Nosto/nosto-magento2#257]
2.7.0 - 2.9.0 version tags contain error in Model/Product/Repository.php line 169, adding filter by unexisting store attribute.
Which leads to error "(Magento\Framework\Exception\LocalizedException): Invalid attribute name: store
I see that fix is done in develop branch. Please release it

**Comment by hannunosto** [comment]
Thanks for reporting this @tereshvti. We have fixed this in https://github.com/Nosto/nosto-magento2/pull/255. We'll roll out a new version next week (week 17) including this fix.
