### ISSUE TITLE
Disable indexing products throws Uncaught TypeError

### ISSUE THREAD

**Issue by esbenboye** [Nosto/nosto-magento2#260]
I'm trying to implement nosto/module-nostotagging:2.10.0, but it comes up with an  "Uncaught TypeError" when trying to disable the indexing of some products.

I've followed the steps in the guide "[How To Disable Indexing For Certain Products](https://github.com/Nosto/nosto-magento2/wiki/How-To-Disable-Indexing-For-Certain-Products)", except I did not make a composer.json. 

My event listener is set up to listen for `nosto_product_load_before` with the following code:

    public function execute(Observer $observer)
    {
        /** @var \Magento\Catalog\Model\Product $product */
        $product = $observer->getData('magentoProduct');
        $type = $product->getTypeId();
        if (in_array($type, $this->ignoreProductTypes)) {
            $modelFilter = $observer->getData('modelFilter');
            $modelFilter->setValid(false);
        }
    }

After looking into the code and debugging, I've come up with the following;
If the listener invalidates the `$modelFilter`, then the `Nosto\Tagging\Model\Product\Builder::build` returns `NULL` to `Nosto\Tagging\Model\Product\Service::processForAccount`.
`processForAccount` continues to check if `$nostoProduct` is not  an instance of `ProductInterface`, which is true, since `$nostoProduct` is `NULL`. 
The `$nostoProduct` is then passed on to `Nosto\Operation\UpsertProduct::addProduct`, which expects an actual product, but receives `NULL`. 
In the end, `addProduct` throws an error because it expects the parameter to be an instance of `Nosto\Types\Product\ProductInterface`. 

Am i missing something, or is this possibly a bug?

**Comment by hannunosto** [comment]
Thanks for reporting this @esbenboye. This indeed is a bug. We will roll out a fix asap.

**Comment by hannunosto** [comment]
This is now fixed in version 2.10.1
