### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by StefanoM2** [Nosto/nosto-magento2#264]
Please could somebody help me, I have this error:

First command setup:upgrade exited successfully with message "nothing to import" however setup:di:compile exited with error and this is message:

Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 54.0 MiBPHP Fatal error:  Trait 'Nosto\Mixins\OauthTrait' not found in /home/lamercer/magento2test.XXXXXX.it/app/code/Nosto/Tagging/Controller/Oauth/Index.php on line 55

**Comment by hannunosto** [comment]
@StefanoM2 thanks for reporting this error. Can you please tell which versions of Magento 2 and Nosto module are you using?

**Comment by hannunosto** [comment]
We could not reproduce this with latest M2 (2.2.4) and latest Nosto module (2.10.1). Let us know if haven't got around this issue with the latest version of Magento 2 and Nosto module
