### ISSUE TITLE
Full reindex causes the MySQL to crash

### ISSUE THREAD

**Issue by srzkptrsk** [Nosto/nosto-magento2#275]
Could you improve your index method (\Nosto\Tagging\Model\Indexer\Product\Indexer::executeFull)? It's really don't work on a large collection, for example, we have 160k products - while execution from CLI we get a crash of mysql. But if we using generators or just foreach per batch (in 10k products) - it's ok.

Another issue -

[2018-06-05 10:37:44] nosto.ERROR: Failed to send 50 products for store XXX (2) Error was Invalid product update payload [] []
[2018-06-05 10:37:44] nosto.ERROR: Nosto\Request\Api\Exception\ApiResponseException: Invalid product update payload in 

For ref, magento-e72f949a

**Comment by chenliangde** [comment]
We will take a look at the indexing issue. For the "Invalid product update payload" issue, we are going to need more information. Please contact nosto support and we will take it from there.

**Comment by supercid** [comment]
Hi @srzkptrsk,
In the mean time you can have a look at this comment by Hannu:
#229 
https://github.com/Nosto/nosto-magento2/issues/229#issuecomment-367595847
