### ISSUE TITLE
Performance issue with loading products one by one instead of all together

### ISSUE THREAD

**Issue by hostep** [Nosto/nosto-magento2#307]
Hi guys!

Using Magento EE 2.2.5, Nosto module is at 2.11.0.
Full page cache is disabled, using a configurable product with 12 associated simple products.
Testing the product detail page.

I've detected a performance issue in [`Nosto\Tagging\Model\Product\Repository::getSkus`](https://github.com/Nosto/nosto-magento2/blob/2.11.0/Model/Product/Repository.php#L224-L227)

The foreach in there is loading a product one at a time, instead of loading them all at once, which results in multiple queries to the database, which can most likely be optimized to a single query to the database.

In my test, this `getSkus` method is called 3 times, the first time it takes ~0.5 seconds, the other two times it goes really fast, because the data is already in memory.

Can you guys try to optimize this bit of the code, so it takes less time to execute?

Thanks!

**Comment by IvanChepurnyi** [comment]
Hi Guys, we experience the same issue on one of our customer website, and your extension produces whopping 2000+ database queries on any configurable product page just to output tags...
