### ISSUE TITLE
Performance issue with buildCustomFields

### ISSUE THREAD

**Issue by hostep** [Nosto/nosto-magento2#308]
Hi guys!

Using Magento EE 2.2.5, Nosto module is at 2.11.0.
Full page cache is disabled, using a configurable product with 12 associated simple products.
Testing the product detail page.

I've detected a performance issue with the [`buildCustomFields`](https://github.com/Nosto/nosto-magento2/blob/2.11.0/Model/Product/Sku/Builder.php#L137) method.
This method is called 12 times (once per simple product), and takes on average ~0.05 seconds. So multiplied by 12, this is 0.6 seconds, which is quite a lot.

I think this can be optimised, in a way that you have to get all attributes you need from all the simple products in one single database query, instead of doing this per product. This probably mean that a lot of code needs to be refactored, as I don't see an easy way of changing this without re-organising the code a bit.

Would be great if you can figure something out for this issue.

Thanks!

**Comment by IvanChepurnyi** [comment]
I think this one is fixed by #593. @hostep can you confirm?

**Comment by hostep** [comment]
Unfortunately I'm no longer working on the project where we used this module. So I'm not able to test again I'm afraid.

**Comment by olsi-qose** [comment]
Hi @IvanChepurnyi , sorry the description of the PR was not verbose. #593 tackles sku and category strings building, but not customFields. We are looking into improving it. We are also open to feedback and suggestions. 
Thank you!

**Comment by IvanChepurnyi** [comment]
I think it is kind of should tackle it as you removed load of simple products from configurable in repository. But it requires some testing.

**Comment by hannunosto** [comment]
As @olsi-qose mentioned above, this should be fixed now.
