### ISSUE TITLE
Performance issue with the nosto_product_sync indexer

### ISSUE THREAD

**Issue by hostep** [Nosto/nosto-magento2#317]
Hi guys!

Using Magento EE 2.2.5, Nosto module is at 2.11.0.
Using a shop with 57225 products, 134 categories, 116 product attributes and 2 storeviews.

It takes about 1 hour and 1 minute to do a full reindex of the `nosto_product_sync` indexer. This is really slow.
The slowest other indexer when performing a full reindex on this shop, is the `catalog_product_attribute` indexer, which only takes about 3 minutes.

Would there be a chance that you guys can try looking into optimizing the indexing speed, because it is really really slow at the moment.

Thank you!

**Comment by hannunosto** [comment]
Hi @hostep, thanks for reporting this issue. We are trying to estimate the magnitude of this problem. Can you please elaborate why would you need to do a full reindex on a regular basis? Of course we see room for improvements here but the full reindex should be ran only if you update attributes for all of the products without using Magento's product model. Or is there some other reasons we are missing here?

**Comment by hostep** [comment]
Hi @hannunosto 

Good question! We actually don't need to run a full reindex on a regular basis. This was probably the first one I ran in a couple of months time. I just thought it was strange that it took so long for that specific indexer to run.

Can you maybe elaborate on what the indexer does exactly? Guessing by its name, it is probably sending a lot of data from the catalog in Magento over to the Nosto servers. But should that really take 1 full hour to do so?
On the same shop, we use another external service, which also first has to sync the entire product data over to their servers for some other marketing related use case, and that one only takes about 6 or 7 minutes, not 1 full hour (but uses a cronjob and not the indexer, not that that matters I think).
That was what seemed odd to me, a couple of minutes versus a full hour, hence we I've opened an issue.

Hope this makes it a bit more clear :)

Thanks!

**Comment by hannunosto** [comment]
Ok, thanks @hostep. Here's some basic info about the indexer: https://github.com/Nosto/nosto-magento2/wiki/Indexer. In practise the indexer is used for sending product data to Nosto over API. The reason the indexer is slower than other indexers is that the product data builder (https://github.com/Nosto/nosto-magento2/blob/master/Model/Product/Builder.php) is rather complex and it needs to perform multiple queries and mangle the data a bit to fit Nosto's needs. Naturally the API calls also add some overhead to the indexer.

As said in the previous comments, there should be no need to run the full reindex for Nosto products unless you make direct database updates or for some other reason the indexer is not working properly. Product data is updated automatically to Nosto as long the products in Magento are updated via Magento's product model.

**Comment by hostep** [comment]
Ok thanks for the info! Will try to remember that when I have to do a full reindex (mostly on local environment, for debugging something non-Nosto-related), I should skip the Nosto indexer.

If you believe that the performance of the indexer is good enough at the moment, then please go ahead and close the issue.

**Comment by hannunosto** [comment]
Thanks @hostep, I'm closing this one now since we already have more specific performance improvement tasks (#308 and #307).
