### ISSUE TITLE
Undefined Constant on Magento Cloud

### ISSUE THREAD

**Issue by lburgosDO** [Nosto/nosto-magento2#356]
Hello,
I installed this on Magento Cloud 2.2.6. When I try to run any of the php bin/magento commands like php bin/magento setup:upgrade, I see this error:

PHP Fatal error:  Uncaught Error: Undefined class constant 'API_EMAIL' in /app/app/code/Nosto/Tagging/Console/Command/NostoAccountConnectCommand.php:117

**Comment by hannunosto** [comment]
Hi @lburgosDO, we need a bit more information about this one. Did you install the extension normally using the composer? And what version of the Nosto M2 module are you using? 

It looks like that for some reason you have outdated Nosto PHP SDK version installed. `Token::API_EMAIL` was added into the SDK in 3.3.2 (https://github.com/Nosto/nosto-php-sdk/releases/tag/3.3.2)

**Comment by lburgosDO** [comment]
Hi @hannunosto,
I am using 2.15.2-beta. I installed it using composer locally in app/code folder. I then pushed those files to the Magento Cloud. For Magento Cloud upgrades, it's better to have less dependencies. So the cleaner I can keep composer.json, the easier it is down the road to upgrade the Cloud.  I did put in the SDK dependecy as follows

"require": {
        "magento/magento-cloud-metapackage": ">=2.2.6 <2.2.7",
        "nosto/php-sdk": "3.3.2"
    },

It upgraded nicely and the 'API_EMAIL' error is now replaced with another.
 Uncaught Error: Undefined class constant 'API_GRAPHQL' 

Can you give me some insight on how to resolve?

Thanks
Lonny

**Comment by hannunosto** [comment]
@lburgosDO you should not define the `nosto/php-sdk` dependency yourself. It's a dependency of Nosto module for M2 (this repo) and the correct version of SDK version is defined here https://github.com/Nosto/nosto-magento2/blob/2.15.2-beta/composer.json#L39
