### ISSUE TITLE
Compiling error on version 3.2.0

### ISSUE THREAD

**Issue by kilis** [Nosto/nosto-magento2#412]
Hello.
Seems that nosto has compiling issue on version 3.2.0 and up:
`Errors during compilation:
    Nosto\Tagging\Helper\Account
        Incorrect dependency in class Nosto\Tagging\Helper\Account in /var/www/store/magento/vendor/nosto/module-nostotagging/Helper/Account.php
\Magento\Framework\UrlInterface already exists in context object`
Can anybody fix it?
Thanks!

**Comment by hannunosto** [comment]
Thanks for reporting @kilis. We will give it a shot and get back to you.

**Comment by kilis** [comment]
@hannunosto 
We are using 2.1.7 version. 
The fix should be easy for this:
        from $this->urlBuilder = $urlBuilder; 
to $this->urlBuilder = $context->getUrlBuilder();
