### ISSUE TITLE
Add to cart button not working

### ISSUE THREAD

**Issue by AndreKlang** [Nosto/nosto-magento2#42]
Hi

In the default template "magento-default" I can enable the add to cart button, it shows up fine but it's onclick is not working.

It is calling ```Nosto.addProductToCart('[ID]', this); return false;```, but ```Nosto``` is undefined.

I'm running Magento 2.1.2, Nosto module 1.1.0

**Comment by hannunosto** [comment]
Hey @AndreKlang, unfortunately "add-to-cart" functionality is not implemented in our Magento 2 extension yet. We are planning to add this feature at some point but we don't have timeline for that yet.
