### ISSUE TITLE
Data upgrades do not run when upgrading from an old version

### ISSUE THREAD

**Issue by tgerulaitis** [Nosto/nosto-magento2#485]
**Magento 2 version(s) used**: 2.1.7
**Extension version(s) affected**: <3.1.0 & <3.5.0

**Description**  
When updating the module from an old version (anything before 3.1.0) to the latest version, the migrations in `Nosto\Tagging\Setup\UpgradeData` do not get run because the version check is using the incorrect comparison operator. This means that the store domain does not get stored in `core_config_data` table, causing a warning in Magento backend, and the customer reference attribute does not get added.

**How to reproduce**  
1. Install module version 3.0.3
2. Run `bin/magento setup:upgrade`
3. Configure Nosto in Magento Backend
4. Install module version 3.7.4
5. Run `bin/magento setup:upgrade`

***Expected outcome:***
After running the upgrade, the store domain should be set in the `nosto_tagging/settings/domain` setting in `core_config_data`, and a new customer attribute `nosto_customer_reference` should be created.

***Actual outcome:***

The store domain is not set, and customer attribute is missing.

**Magento 2 mode**
- [x] Developer 
- [x] Production

**Full page cache**
- [ ] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ ] Update On Save  
- [ ] Update By Schedule

**Possible Solution**  
The comparison operator used in the `version_compare` function in `Nosto\Tagging\Setup\UpgradeData` should be `<=` instead of `>=`. The version provided by the `$context` object in that class is the current version in the database, not current version in the module files, so when upgrading from a really old version (e.g. `3.0.3`), neither of the `if` statements passes.

**Additional context**

**Comment by olsi-qose** [comment]
Thank you @tgerulaitis for opening the issue. 

We will release a hotfix for this issue soon.
