### ISSUE TITLE
Add orchestration when to resend Nosto tagging in KnockoutJS

### ISSUE THREAD

**Issue by supercid** [Nosto/nosto-magento2#503]
**Is your feature request related to a problem? Please describe.**
With the current implementation, we might end up making 3 push requests for each page load. The reason for this is that each KnockoutJS component sends the tagging or loads recommendations individually without knowing if other components are ready or not.

**Describe the solution you'd like**
- Add an orchestrator (could be JS component that holds information what knockout components must be rendered
- The orchestrator must be injected into all Knockout components that need to reload recos / send additional data
- The orchestrator keeps on track what components will be loaded and after the last component is loaded recos can be re-loaded

**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by mridang** [comment]
Is this really an issue? @hannunosto please comment. Close if not needed

**Comment by hannunosto** [comment]
This has not been an issue really. We'll circle back if this bubbles up.
