### ISSUE TITLE
Visitor and cart checksum tagging doesn't work when Nosto cookies are deleted 

### ISSUE THREAD

**Issue by fairlane** [Nosto/nosto-magento2#512]
**Magento 2 version(s) used**: all
**Extension version(s) affected**: all

**Description**  
Nosto cart and customer checksum is not reset if Nosto cookies are cleared.

**How to reproduce**  

1. Open any product page and add the product to cart
2. Clear the Nosto cookies
3. Old checksum is still present in tagging 

**Magento 2 mode**
- [x] Developer 
- [x] Production

**Full page cache**
- [x] Enabled 
- [x] Disabled

**Nosto indexer mode**
- [x] Update On Save  
- [x] Update By Schedule

**Possible Solution**  
Ditch the hcid tagging all together. It's only needed for preventing FPC to cache the checksums and in M2 customer tagging and cart tagging are using sections and those are cached only for the current session.

**Comment by supercid** [comment]
Already fixed
