### ISSUE TITLE
Supplier cost is not working for configurable products when Cost attribute is used

### ISSUE THREAD

**Issue by fairlane** [Nosto/nosto-magento2#513]
**Magento 2 version(s) used**: all
**Extension version(s) affected**: all

**Description**  
We are not picking up the supplier cost correctly for configurable products when "Cost" attribute is set to define the supplier cost.
  
![Configuration___Settings___Stores___Magento_Admin](https://user-images.githubusercontent.com/15191701/62604419-b6d40e80-b900-11e9-8a47-675968950379.png)

**How to reproduce**  
1. Define "Cost" attribute as the source for "Supplier cost"
2. Input "Cost" attribute for all variations for a configurable product
3. Send product over API or use the export controller to debug the product data -> supplier cost is missing
 
**Magento 2 mode**
- [x] Developer 
- [x] Production

**Full page cache**
- [x] Enabled 
- [x] Disabled

**Nosto indexer mode**
- [x] Update On Save  
- [x] Update By Schedule

**Possible Solution**  
We need to get the attribute defining supplier cost from the cheapest SKU (not the min supplier cost) and use that as a parent product's supplier cost. Note that this should be only fallback method if the attribute defining supplier cost is not preset in the parent product.

**Comment by mridang** [comment]
@hannunosto what's the status with this?

**Comment by hannunosto** [comment]
This has not been done yet
