### ISSUE TITLE
List price is not mapped to Nosto

### ISSUE THREAD

**Issue by oostman** [Nosto/nosto-magento2#53]
Tested issue on Magento EE 2.1.5 with plugin version 1.2.0

**Comment by hannunosto** [comment]
This applies to all configurable products. The custom option `simple_product` seems to be null in https://github.com/magento/magento2/blob/2.1/app/code/Magento/ConfigurableProduct/Model/Product/Type/Configurable/Price.php#L42. 

This needs a bit more investigating if it's a bug or a configuration issue.
