### ISSUE TITLE
Setup:upgrade results in "Class Nosto\Tagging\Helper\Account\Proxy does not exist" during install

### ISSUE THREAD

**Issue by davidpixie** [Nosto/nosto-magento2#592]
**Magento 2 version(s) used**: 2.3.2
**Extension version(s) affected**: 3.9.0

**Description**  
I'm attempting to install the module on my 2.3.2 site but am getting the following error when running setup:upgrade to install:

_In_ ClassReader.php line 19:
Class Nosto\Tagging\Helper\Account\Proxy does not exist_

**How to reproduce**  
Clean install of Magento 2.3.2. Enable module and run setup:upgrade

**Magento 2 mode**
- [x] Developer 

**Full page cache**
- [x] Disabled

**Nosto indexer mode**
N/A

**Comment by davidpixie** [comment]
Hi @supercid 
Thanks for this - it didn't get past the `setup:upgrade` step at all. 
I notice in the instructions it says it "can only be installed via composer". I tried installing via putting the module into the `app/code` directory manually. Could that be the problem?
Thanks!

**Comment by olsi-qose** [comment]
Hi @davidpixie 
Copying the module directly to `app/code` will also lead to other issues like missing dependencies like our `php-sdk`. 
Please install it through git by following our wiki article: https://github.com/Nosto/nosto-magento2/wiki/Installing

**Comment by davidpixie** [comment]
Thanks @olsi-qose 
I'll install via composer and will let you know how it goes :-)

**Comment by davidpixie** [comment]
Hi again @olsi-qose - works fine while installing with composer, thanks.
