### ISSUE TITLE
nosto_product_sync index is stuck and goes in infinite loop

### ISSUE THREAD

**Issue by dupadhyay3** [Nosto/nosto-magento2#611]
**Magento 2 version(s) used**: 2.3.2
**Extension version(s) affected**: 3.10.1

**Description**  

I have used both mode (_Update By Schedule_ / _Update On Save_) for Nosto indexer. When I try to run full re-indexing or run this command:` bin/magento index: reindex nosto_product_sync` , then `nosto_product_sync` index stuck in processing or it will take up minimum 4 hours to complete the indexing process.

**How to reproduce**  

1. Install fresh Magento 2.3.2 with Nosto Tagging 3.10.1 and configure.
2. Change `nosto_product_sync` indexer mode to any mode from _Update By Schedule_ / _Update On Save_
3. Run re-indexing command: ` bin/magento index: reindex nosto_product_sync`

**Magento 2 mode**
- [X] Developer 
- [X] Production

**Full page cache**
- [X] Enabled 
- [X] Disabled

**Nosto indexer mode**
- [X] Update On Save  
- [X] Update By Schedule

**Possible Solution**  

Reason: In indexer.php files executeFull() method is set page size for product collection before do.. while.. to get last page number for do..while..
But inside do block Nosto Team forgot to set page size for product collection. Because of this, if in magento store there is 41000 products, and batch size is set to 1000 then do while loop will execute 41 time and inside do..while.. structure, page size is not set to product collection and every time of loop execution it will sync 41000 product for 41 time.

**Comment by supercid** [comment]
Hi @dupadhyay3 
We are aware of this issue and we did a full re-implementation of the indexer available as a beta release here:
https://github.com/Nosto/nosto-magento2/releases/tag/4.0.0-rc5

Would you like to give it a try and let us know how it goes?

**Comment by hannunosto** [comment]
Thanks for reporting @dupadhyay3, we'll make a fix

**Comment by supercid** [comment]
Merged and released here: https://github.com/Nosto/nosto-magento2/releases/tag/3.10.2

Thanks again for your contribution @dupadhyay3 🎉
