### ISSUE TITLE
Build shortest product url

### ISSUE THREAD

**Issue by olsi-qose** [Nosto/nosto-magento2#619]
**Magento 2 version(s) used**: x.y.z
**Extension version(s) affected**: x.y.z

**Description**  
Product builder fetches the first row out of all the rows for product url_rewrite.
In case the url without categories has been deleted and added again later, it will not be fetched first.

**How to reproduce**  
1. Go to Marketing -> SEO & Search -> Url Rewrites
2. Delete the shortest form for Url Rewrites. 
3. Create it again

Visit PDP and check the product tagging for the product url. It will contain categories in it. 

**Magento 2 mode**
- [ ] Developer 
- [ ] Production

**Full page cache**
- [ ] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ ] Update On Save  
- [ ] Update By Schedule

**Possible Solution**  

**Additional context**

**Comment by supercid** [comment]
What do you mean by
 > 2. Delete the shortest form for Url Rewrites.
I couldn't find this option to test your PR.

![image](https://user-images.githubusercontent.com/2778820/71518777-21401800-28bd-11ea-945e-d0e6b91b5075.png)
![image](https://user-images.githubusercontent.com/2778820/71518794-3c128c80-28bd-11ea-94e8-f95bf2798c40.png)
