### ISSUE TITLE
What does "real-time cart updates to Nosto" mean and what is the performance impact?

### ISSUE THREAD

**Issue by StanislavKraus** [Nosto/nosto-magento2#633]
**Documentation issue**

https://github.com/Nosto/nosto-magento2/wiki/Configuring#feature-flags
In this section, not all of the features are explained. 
Can you please explains at least this one for now?

**Comment by hannunosto** [comment]
"Real-time cart updates to Nosto" is (or was) an experimental feature where we send the cart contents to Nosto in server side. We have however decided not to move forward with this feature and the feature flag will be removed in future releases
