### ISSUE TITLE
Setup:upgrade fail due to Street Address field

### ISSUE THREAD

**Issue by KevinOxwork** [Nosto/nosto-magento2#647]
**Magento 2 version(s) used**: 2.3.4
**Extension version(s) affected**: 4.0.0

**Description**  
After composer update, we make bin/magento setup:upgrade and got "Module 'Nosto_Tagging':
Upgrading data.. "Street Address" cannot contain more than 2 lines." error. We have to downgrade to nosto tagging 3.10.5 :(

**How to reproduce**  

**Magento 2 mode**
- [x] Developer

**Full page cache**
- [x ] Disabled

**Comment by supercid** [comment]
Hi @KevinOxwork, we already have an issue open for this. I'll close this one and we can follow up on #646
