### ISSUE TITLE
Issue nosto/module-nostotagging (3.10.5 => 4.0.4)

### ISSUE THREAD

**Issue by m60digital** [Nosto/nosto-magento2#656]
**Magento 2 version(s) used**: 2.3.4
**Extension version(s) affected**: 4.0.4

**Description**  
We are Magento 2.3.4 and updating nosto/module-nostotagging (3.10.5 => 4.0.4) When I run bin/magento setup:upgrade, I get the following error:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'libertyinlove2.nosto_tagging_product_cache' doesn't exist, query was: DESCRIBE `nosto_tagging_product_cache`

**How to reproduce**  
- Install Magento 2.3.4
- Install 3.10.5 nosto/module-nostotagging 
- Composer update to 4.0.4
- Run bin/magento setup:upgrade

**Magento 2 mode**
- [x] Developer 
- [x] Production

**Full page cache**
- [x] Enabled 
- [x] Disabled

**Nosto indexer mode**
- [ ] Update On Save  
- [x] Update By Schedule

**Possible Solution**  

**Additional context**

**Comment by supercid** [comment]
This is now fixed in 4.0.5! https://github.com/Nosto/nosto-magento2/releases/tag/4.0.5

Please upgrade your local installation.
Thanks for reporting it! 😃
