### ISSUE TITLE
PHP 7.2 compliance

### ISSUE THREAD

**Issue by sdesmet** [Nosto/nosto-magento2#658]
```
$ composer show

nosto/module-nostotagging                      4.0.4
nosto/php-sdk                                  4.0.10 
```

When running PHP codesniffer for 7.2 compliance, I get many these because of "Object" used in the namespace.

`FILE: /vendor/nosto/php-sdk/src/Object/ExchangeRateCollection.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 37 | ERROR | 'object' is a soft reserved keyword as of PHP version 7.0 and a reserved keyword as of PHP version 7.2 and should not be used to name a class, interface or trait or as part of a namespace
    |       | (T_NAMESPACE)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------`

**Comment by supercid** [comment]
We already have a pull request to solve those sniffer issues: #627
We should get back to it soon :)

**Comment by sdesmet** [comment]
Sorry, missed that. Thanks.

I'll close this one then.
