### ISSUE TITLE
Base table or view not found: nosto_tagging_product_cache

### ISSUE THREAD

**Issue by webamondo** [Nosto/nosto-magento2#660]
**Magento 2 version(s) used**: 2.3.4
**Extension version(s) affected**: 4.0.5

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nosto_tagging_product_cache' doesn't exist, query was: DESCRIBE `nosto_tagging_product_cache`

**Description**  
Just upgraded to 4.0.5 and when executing bin/magento setup:upgrade I get the following error 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nosto_tagging_product_cache' doesn't exist, query was: DESCRIBE `nosto_tagging_product_cache`

**How to reproduce**  

**Magento 2 mode**
- [ Y] Developer 
- [ Y] Production

**Full page cache**
- [ Y] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ ] Update On Save  
- [ Y] Update By Schedule

**Comment by supercid** [comment]
Hi @webamondo, From which version did you upgrade from?
One thing you can do to create the table is to modify the `schema_version` and `data_version` on the `setup_module` to 3.10.5 and run the `setup:upgrade` command again.
```sql
UPDATE setup_module SET `schema_version` = '3.10.5', `data_version` = "3.10.5" WHERE `module` = "Nosto_Tagging"
```
We had a bug from version 4.0.0 that this table wasn't being created and this got fixed on 4.0.5. However, if you upgrade from 4.0.0~4.0.4 might be that the table wasn't there. I'll make a fix for this comparison later.

**Comment by webamondo** [comment]
Hi @supercid I upgraded from 4.0.3.

I'll give your SQL query ago.

**Comment by webamondo** [comment]
@supercid just confirming that 1 your SQL query worked and allowed me to install and 2 it was version 4.0.1 not 4.0.3 like I had previously stated

**Comment by supercid** [comment]
Great! I'll close this one as done then.
