### ISSUE TITLE
Class Nosto\Tagging\Model\Product\Cache\CacheRepository\Proxy does not exist

### ISSUE THREAD

**Issue by szreka** [Nosto/nosto-magento2#662]
**Magento 2 version(s) used**: 2.3.2, 2.3.3
**Extension version(s) affected**: 4.0.5

**Description**  
After upgrading to 4.0.5 we noticed that in the `cron_schedule` table the `nosto_rebuild_product_data` is stuck with the error message of `Class Nosto\Tagging\Model\Product\Cache\CacheRepository\Proxy does not exist`. In developer mode the class gets generated, but when running `setup:di:compile`, it doesn't.

**How to reproduce**  
Run the `nosto_rebuild_product_data` cron job in production mode.

**Magento 2 mode**
- [ ] Developer 
- [x] Production

**Full page cache**
- [x] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [x] Update On Save  
- [x] Update By Schedule

**Comment by hannunosto** [comment]
This sounds weird. The `setup:di:compile` should generate the proxy classes. Could you please post detailed steps how to reproduce this. Basically what we'd like to understand is the full deployment process. Did you for example run `setup:di:compile` command after the deployment as well?

**Comment by szreka** [comment]
I've ran `setup:di:compile` locally and it didn't get generated. Our live environment is on Magento cloud, we can't run it after the deployment as it's read-only.

**Comment by szreka** [comment]
So what I've done:
- Seen the error message on production
- Tried to recreate it locally, but it was working fine
- Deleted generated folder, and ran `setup:di:compile` 
- The file was missing from the generated folder even though other proxies were there (ie: `Nosto\Tagging\Helper\Data`)
- Also along with `Nosto\Tagging\Model\Product\Cache\CacheRepository\Proxy`, `Nosto\Tagging\Model\Service\Cache\CacheService\Proxy` is missing

**Comment by supercid** [comment]
Hi @szreka,
I've tried to reproduce here and checked the logs from Apache and var/log folder withing Magento, no errors reported.

Are you using Magento Cloud? Are the generated files committed and if so does it include the files that are missing?

What I did was:
- Set Magento mode to production
- Set the data indexer to be built on cron
- Ran `bin/magento cron:run`
- Checked the logs, all fine.

**Comment by szreka** [comment]
Hi @supercid,
Did you remove the `generated` folder before setting Magento to `production` mode? I noticed the issue when running `setup:di:compile`, when being on `developer` mode, the files get generated on the fly.

We don't commit generated files - they are generated during the deploy.

**Comment by supercid** [comment]
Hi @szreka,
I did remove the generated folder and set it to production right after.
The files aren't there, but they are created as soon as you run the cronjob(In production and development modes).
Can you try to add a step that runs the cronjob when you deploy to ensure that those files are created and let me know if it fixes the issue? 
I've tried in our Magento cloud instance and went fine, so I'm just trying to isolate the problem at this point.

**Comment by szreka** [comment]
Hi @supercid ,
Magento Cloud is a read-only, these files need to be created before the cron runs as they won't get generated - any other way to get around it? We really wouldn't want to commit the generated folder.

**Comment by hannunosto** [comment]
Hi @szreka, sorry for the delay in getting to this. I got the error finally reproduced. We'll make a fix asap.

**Comment by hannunosto** [comment]
This is now fixed in 4.0.6. Please drop a comment here if this does not do the job.
