### ISSUE TITLE
Reset Nosto settings link on backend notifications

### ISSUE THREAD

**Issue by barbanet** [Nosto/nosto-magento2#667]
**Magento 2 version(s) used**: 2.3.4
**Extension version(s) affected**: 4.0.1

**Description**  
If you need to reset your account, the admin notification message redirects you to the frontend to execute, for example: https://www.example.com/nosto/account/index/store/1/

**How to reproduce**  
You need to configure your store for one domain first and then change the domain.
The message displayed becasue Invalid Account will do the rest.

**Magento 2 mode**
- [X] Developer 
- [X] Production

**Full page cache**
- [X] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ ] Update On Save  
- [ ] Update By Schedule

**Possible Solution**  
I didn't tried but I guess the problem is here: https://github.com/Nosto/nosto-magento2/blob/develop/Helper/Account.php#L362
The UrlBuilder is an instance of Magento\Framework\Url and that why the link redirects to the store front and return a 404 (and the action can't be completed)

**Comment by olsi-qose** [comment]
Hi @barbanet thank you for reporting the issue!
I was able to reproduce it, will have a look and come back when it is solved.

**Comment by mridang** [comment]
@olsi-qose is this done?

**Comment by olsi-qose** [comment]
Yes
