### ISSUE TITLE
Remove the sku string usage from DefaultStockProvider

### ISSUE THREAD

**Issue by hannunosto** [Nosto/nosto-magento2#683]
**Is your feature request related to a problem? Please describe.**
Method `Magento\CatalogInventory\Model\Stock\Status::getSku()` doesn't exist and it's called here: https://github.com/Nosto/nosto-magento2/blob/develop/Model/Service/Stock/Provider/DefaultStockProvider.php#L134. It falls back to a magic method and we should not rely on the fact that the data is there. 

**Describe the solution you'd like**
Remove the sku (string) completely as it's not needed.  

**Additional context**
<img width="992" alt="Release_5_0_0_by_hannunosto_·_Pull_Request__681_·_Nosto_nosto-magento2" src="https://user-images.githubusercontent.com/15191701/83255856-e1f25c00-a1b9-11ea-8072-59d6eeccefcd.png">

**Comment by mridang** [comment]
Is this done?

**Comment by hannunosto** [comment]
This is done
