### ISSUE TITLE
Index CL tables become very large

### ISSUE THREAD

**Issue by sbailey88** [Nosto/nosto-magento2#723]
**Magento 2 version(s) used**: 2.3.3
**Extension version(s) affected**: 5.0.6

**Description**  
nosto_index_product_data_cl and nosto_index_product_invalidate_cl become full and extremely large, over 18 million records in a few months

**How to reproduce**  
We have found the disk space full and noticed that one of the nosto cl tables was over 4GB.

**Magento 2 mode**
- Production

**Full page cache**
- Enabled 

**Nosto indexer mode**
- Update On Save

**Comment by sbailey88** [comment]
adding to the comment an example of how large the table has got;

MariaDB [xxxx]> SELECT
    ->   TABLE_NAME AS `Table`,
    ->   ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024) AS `Size (MB)`
    -> FROM
    ->   information_schema.TABLES
    -> WHERE
    ->   TABLE_SCHEMA = "xxxx"
    -> ORDER BY
    ->   (DATA_LENGTH + INDEX_LENGTH)
    -> DESC;
+-----------------------------------------------------------+-----------+
| Table                                                     | Size (MB) |
+-----------------------------------------------------------+-----------+
| nosto_index_product_invalidate_cl                         |      8857 |

**Comment by olsi-qose** [comment]
Hi @sbailey88

Both `nosto_index_product_data_cl` and `nosto_index_product_invalidate_cl` tables are used in v4.x.x releases of the module. Those indexers have been renamed and refactored in v5. It seems that those tables have not been dropped after upgrading the module and the mysql triggers are still active. As they are not being used, deleting them would remove the issue. 

https://github.com/Nosto/nosto-magento2/blob/4.0.10/etc/mview.xml#L37

Sorry for the late reply!

**Comment by supercid** [comment]
Stale
