### ISSUE TITLE
\Nosto\Tagging\Observer\Order\Save::getCustomerReference should check if their is a customer_id on the order

### ISSUE THREAD

**Issue by steven-hoffman-jomashop** [Nosto/nosto-magento2#736]
**Magento 2 version(s) used**: 2.3.5
**Extension version(s) affected**: 5.0.1 (Code is the same on 5.2.9)

**Description**  
getCustomerReference should check if their is a customer_id on the order.
There is no reason to try to load a customer that can not exist and then log the missing customer error

**How to reproduce**  
Place an order as a guest

**Magento 2 mode**
- [x] Developer 
- [x] Production

**Full page cache**
- [x] Enabled 
- [x] Disabled

**Nosto indexer mode**
- [x] Update On Save  
- [x] Update By Schedule

**Possible Solution** 
Add code to getCustomerReference
`        if(!isset($customerId)){
            return null;
        }`

**Comment by steven-hoffman-jomashop** [comment]
Note: https://github.com/Nosto/nosto-magento2/blob/6c24e46536dc91bf3d5cf39311e574a09cb19aad/Observer/Order/Save.php#L209 can be modified by adding a guard clause `if(!isset($customerId)){ return null; }`

**Comment by olsi-qose** [comment]
Hi @steven-hoffman-jomashop 

Do you know if the customer has refused the cookies. This line https://github.com/Nosto/nosto-magento2/blob/develop/Observer/Order/Save.php#L236 should return a Nosto Customer Object, which contains the customer id (even it's a guest).

Are you using multi channel order tracking? Or are all orders coming through the website. You can disable the flag so the code will not end up in that path unless necessary https://github.com/Nosto/nosto-magento2/blob/develop/Observer/Order/Save.php#L245

**Comment by steven-hoffman-jomashop** [comment]
> Are you using multi channel order tracking?

I am not sure, we are using the Magento2 PWA frontend, so cookies may not be set in the same manner as a standard M2 install.

> You can disable the flag so the code will not end up in that path unless necessary

 We have applied a patch to mitigate the issue.
The patch adds a guard clause to avoid triggering an error when the customer id is missing on the order. 

 ```
 --- a/Observer/Order/Save.php
+++ b/Observer/Order/Save.php
@@ -209,6 +209,9 @@
     private function getCustomerReference(Order $order)
     {
         $customerId = $order->getCustomerId();
+        if(!isset($customerId) || $customerId === ''){
+            return null;
+        }
         $nostoCustomerId = null;
         try {
             $magentoCustomer = $this->magentoCustomerRepository->getById($customerId);
```

Would recommend adding a similar change to the mainline to harden the code. (The exact reason why cookie is missing are varied).

**Comment by steven-hoffman-jomashop** [comment]
Hi, is there any update on this issue?
Is there any further information you might need?

**Comment by mohammedTBB** [comment]
Hi,

I am also getting the exact same error when entering checkout, the error is generating in system.log,
And it dose not allow to make order with bank transfer or credit card.

**Comment by supercid** [comment]
This is now merged and will be available on our next release. Thank you all for pointing that out!
