### ISSUE TITLE
Call to undefined method Nosto\Tagging\Logger\Logger::warn()

### ISSUE THREAD

**Issue by mohammedTBB** [Nosto/nosto-magento2#783]
**Magento 2 version(s) used: 2.4.4
**Extension version(s) affected**: 6.0.3

**Description**  
An error appear in the checkout when clicking at "create order"
 
![image](https://user-images.githubusercontent.com/66772877/177806985-f79f88c9-5b1e-4123-bb2f-d762554b2198.png)

in system.log an error of nosto generated:
[2022-07-07T15:01:58.974396+00:00] main.CRITICAL: Error: Call to undefined method Nosto\Tagging\Logger\Logger::warn() in /var/www/html/magento2-gymcompany/vendor/nosto/module-nostotagging/Observer/Order/Save.php:279

**How to reproduce**  
-- add produc to the cart
-- go to checkout
-- create order

**Magento 2 mode**
- [ - ] Developer 
- [ - ] Production

**Full page cache**
- [ - ] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ - ] Update On Save  
- [ ] Update By Schedule

**Possible Solution**  
we have noticed that the class used for logging is "Nosto\Tagging\Logger\Logger"
and the father of this class "Monolog\Logger"
none of these classes have function "warn" but there is function "warning" that could be used

- so line 279 -> $this->logger->warn(
 could be changed to  -> $this->logger->warning(

**Comment by supercid** [comment]
Fixed by #784
