### ISSUE TITLE
Error in Nosto\Tagging\CustomerData\HashedTagging::generateVisitorChecksum()

### ISSUE THREAD

**Issue by khnaim** [Nosto/nosto-magento2#789]
**Magento 2 version(s) used**: Adobe Commerce ver. 2.4.5
**Extension version(s) affected**: @stable (6.1.0)

**Description**  

I have this error:

TypeError: Nosto\Tagging\CustomerData\HashedTagging::generateVisitorChecksum(): Argument #1 ($string) must be of type string, null given, called in /app/vendor/nosto/module-nostotagging/CustomerData/CustomerTagging.php on line 87 and defined in /app/vendor/nosto/module-nostotagging/CustomerData/HashedTagging.php:55
Stack trace:
#0 /app/vendor/nosto/module-nostotagging/CustomerData/CustomerTagging.php(87): Nosto\Tagging\CustomerData\HashedTagging->generateVisitorChecksum(NULL)
#1 /app/vendor/magento/module-customer/CustomerData/SectionPool.php(90): Nosto\Tagging\CustomerData\CustomerTagging->getSectionData()
#2 /app/vendor/magento/module-customer/CustomerData/SectionPool.php(60): Magento\Customer\CustomerData\SectionPool->getSectionDataByNames(Array)
#3 /app/vendor/magento/module-customer/Controller/Section/Load.php(78): Magento\Customer\CustomerData\SectionPool->getSectionsData(Array, false)
#4 /app/vendor

**How to reproduce**  

in /customer/account/
**Magento 2 mode**
- [ ] Production

**Full page cache**
- [ ] Enabled 

**Nosto indexer mode** 
- [ ] Update By Schedule

**Possible Solution**  

**Additional context**

**Comment by dairbuirabass** [comment]
Hi @khnaim We released a fix for this issue in our latest release: [6.1.3](https://github.com/Nosto/nosto-magento2/releases/tag/6.1.3)
