### ISSUE TITLE
Not Able To Upgrade Magento Version As symfony/console set under conflict in composer.lock under symfony/http-kernel 

### ISSUE THREAD

**Issue by sprajapat770** [Nosto/nosto-magento2#835]
**Magento 2 version(s) used**: 2.4.5-p4
**Extension version(s) affected**: 7.2.1 or 7.3.1

**Description**  
Not Able To Upgrade Magento Version At 2.4.6-p3 due to conflict.

magento/product-community-edition 2.4.6-p3 requires symfony/console ^5.4 -> found symfony/console[v5.4.0-BETA1, ..., v5.4.28] but these were not loaded, likely because it conflicts with another require.

**How to reproduce**  
1. set up magento version 2.4.5-p5
2. setup your nosto tagging module version 7.3.1 via composer
3. upgrade magento version to 2.4.6-p3

**Magento 2 mode**
- [ x ] Developer 
- [ ] Production

**Full page cache**
- [ ] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ ] Update On Save  
- [ ] Update By Schedule

**Possible Solution**  
Either Remove composer.lock or remove  symfony/http-kernel or launch new nosto tagging version with supported 2.4.6-p3

**Additional context**

**Comment by supercid** [comment]
Hi @sprajapat770 
Thanks for the report! I'll be reviewing this sometime next week.
BR!

**Comment by supercid** [comment]
Hi @sprajapat770 
Our latest 7.4 release is now fully compatible with magento 2.4.6, please give it another try.
BR,

**Comment by surajnextbits** [comment]
@supercid thanks
