### ISSUE TITLE
Can we seprate GraphQl Code

### ISSUE THREAD

**Issue by sprajapat770** [Nosto/nosto-magento2#836]
**Is your feature request related to a problem? Please describe.**
Impossible to process constructor argument Parameter #0 [ <required> Magento\CatalogGraphQl\Model\Resolver\Products\SearchResultFac   
  tory $searchResultFactory ] of Nosto\Cmp\Plugin\CatalogGraphQl\Products\Query\Search class

**Describe the solution you'd like**
I would like to get separate nosto/module-nostocmp module for graphql so i can avoid uses of graphql

**Comment by supercid** [comment]
Hi @sprajapat770 
We have a separate module for CMP:
https://github.com/Nosto/nosto-magento2-cmp

**Comment by sprajapat770** [comment]
Thank you & sorry i created wrong ticket 😉
