### ISSUE TITLE
Improvements for after events: add magento objects

### ISSUE THREAD

**Issue by vmalyk** [Nosto/nosto-magento2#85]
For extending Nosto data need to reload magento object and it can decrease performance on  build data. If you add original object to events It`ll provide more clear extending for data. For example, https://github.com/Nosto/nosto-magento2/blob/develop/Model/Product/Builder.php#L197 add:
$this->eventManager->dispatch('nosto_product_load_after', ['nostoData' => $nostoProduct, 'product' => $product]);

**Comment by mridang** [comment]
@vmalyk Good point. We'll do this ASAP.
